# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1d6d193683aaa23c26ca9802f26a4d0d209211a3f5cb602d0a0cb38c2437c16fb48f437ca689ee2e3832634022236d7ff586e4453839ce489bcb3cab153d9ff

test:
  secret_key_base: 13aa701b60897d622dbc891f6527272e5b9eacc95d06e71863418305c3ed33551559f18172e8337e444cba27995124ba790c31ee17ccc00dc633107852262bee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
